export const discordFilePaths: string[] = [
  "Assembly/Source/Bot.cpp",
  "CPP/MyBot/MyBot.cpp",
  "Clojure/src/discord_bot/core.clj",
  "CoffeeScript/src/main.coffee",
  "Crystal/src/gembot/bot.cr",
  "Dart/lib/ping.dart",
  "D/source/app.d",
  "Elixir/lib/thonk/commands/helper.ex",
  "FSharp/FS.FinkSharp/BotCore.fs",
  "Gleam/bot.gleam",
  "Go/bot/bot.go",
  "Groovy/src/main.groovy",
  "Haskell/src/Gundyr.hs",
  "Haxe/bot.hx",
  "Java/src/main/java/org/botexample/DiscordBot.java",
  "JavaScript/src/index.js",
  "Julia/src/main.jl",
  "kotlin/template/App.kt",
  "Lua/basicdiscordbot.lua",
  "Nim/bot.nim",
  "PHP/src/Bot.php",
  "Pascal/discord.pas",
  "Perl/discord.pl",
  "Python/bot.py",
  "R/bot.R",
  "Ruby/lib/src/index.rb",
  "Rust/src/bot.rs",
  "Scala/bot/src/main/scala/science/wasabi/tini/bot/BotMain.scala",
  "Swift/Bot_teste/Sources/Bot/main.swift",
  "TypeScript/src/bot/client/Client.ts",
  "V/main.v",
  "Zig/src/main.zig",
  "CSharp/DiscordBotTemplate/Services/StartupService.cs",
];

export const githubFilePaths: string[] = [
  "data/CSharp/first.cs",
  "data/CSharp/second.cs",
  "data/CSharp/third.cs",
  "data/CSharp/fourth.cs",
  "data/CSharp/five.cs",

  "data/CPP/one.cpp",
  "data/CPP/two.cpp",
  "data/CPP/three.cpp",
  "data/CPP/four.cpp",
  "data/CPP/five.cpp",

  "data/Elixir/one.ex",
  "data/Elixir/two.ex",
  "data/Elixir/three.ex",
  "data/Elixir/four.ex",
  "data/Elixir/five.ex",

  "data/Go/one.go",
  "data/Go/two.go",
  "data/Go/three.go",
  "data/Go/four.go",
  "data/Go/five.go",

  "data/Haskell/one.hs",
  "data/Haskell/two.hs",
  "data/Haskell/three.hs",
  "data/Haskell/four.hs",
  "data/Haskell/five.hs",

  "data/Java/one.java",
  "data/Java/two.java",
  "data/Java/three.java",
  "data/Java/four.java",
  "data/Java/five.java",

  "data/JavaScript/one.js",
  "data/JavaScript/two.js",
  "data/JavaScript/three.js",
  "data/JavaScript/four.js",
  "data/JavaScript/five.js",

  "data/PHP/one.php",
  "data/PHP/two.php",
  "data/PHP/three.php",
  "data/PHP/four.php",
  "data/PHP/five.php",

  "data/Python/one.py",
  "data/Python/two.py",
  "data/Python/three.py",
  "data/Python/four.py",
  "data/Python/five.py",

  "data/Ruby/one.rb",
  "data/Ruby/two.rb",
  "data/Ruby/three.rb",
  "data/Ruby/four.rb",
  "data/Ruby/five.rb",
];
