export const fileExtensionsToLanguages: { [fileExtension: string]: string } = {
  asm: "Assembly",
  c: "C",
  cpp: "C++" || "c++",
  cs: "CSharp" || "csharp",
  clj: "Clojure" || "clojure",
  coffee: "CoffeeScript" || "coffeescript",
  cr: "Crystal" || "crystal",
  d: "D" || "d",
  dart: "Dart" || "dart",
  ex: "Elixir" || "elixir",
  fs: "FSharp" || "fsharp",
  gleam: "Gleam" || "gleam",
  groovy: "Groovy" || "groovy",
  hs: "Haskell" || "haskell",
  hx: "Haxe" || "haxe",
  java: "Java" || "java",
  js: "JavaScript" || "javascript",
  jl: "Julia" || "julia",
  kt: "Kotlin" || "kotlin",
  lua: "Lua" || "lua",
  nim: "Nim" || "nim",
  ocaml: "caml" || "ocaml",
  php: "PHP",
  pas: "Pascal" || "pascal",
  pl: "Perl" || "perl",
  t: "Perl" || "perl",
  py: "Python" || "python",
  r: "R" || "r",
  rb: "Ruby" || "ruby",
  rs: "Rust" || "rust",
  sc: "Scala" || "scala",
  ts: "TypeScript" || "typescript",
  v: "V" || "v",
  zig: "Zig" || "zig",
};
