export const fileExtensionsToLanguages: { [fileExtension: string]: string[] } = {
  asm: ["Assembly", "assembly"],
  c: ["C"],
  cpp: ["C++","c++"],
  cs: ["CSharp","csharp"],
  clj: ["Clojure", "clojure"],
  coffee: ["CoffeeScript", "coffeescript"],
  cr: ["Crystal", "crystal"],
  d: ["D"],
  dart: ["Dart"],
  ex: ["Elixir", "elixir"],
  fs: ["FSharp", "fsharp"],
  gleam: ["Gleam"],
  go: ["Go"],
  groovy: ["Groovy"],
  hs: ["Haskell", "haskell"],
  hx: ["Haxe", "haxe"],
  java: ["Java",],
  js: ["JavaScript", "javascript"],
  jl: ["Julia", "julia"],
  kt: ["Kotlin", "kotlin"],
  lua: ["Lua"],
  nim: ["Nim"],
  ocaml: ["caml"],
  php: ["PHP"],
  pas: ["Pascal", "pascal"],
  pl: ["Perl", "perl"],
  t: ["Perl", "perl"],
  py: ["Python", "python"],
  r: ["R"],
  rb: ["Ruby", "ruby"],
  rs: ["Rust", "rust"],
  sc: ["Scala", "scala"],
  ts: ["TypeScript", "typescript"],
  v: ["V"],
  zig: ["Zig"],
};
