export const fileExtensionsToLanguages: { [fileExtension: string]: string[] } = {
  asm: ["ASM", "Assembly", "assembly"],
  c: ["C"],
  cpp: ["CPP", "C++","c++"],
  cs: ["CS", "CSharp","csharp"],
  clj: ["CLJ", "Clojure", "clojure"],
  coffee: ["COFFEE", "CoffeeScript", "coffeescript"],
  cr: ["Crystal", "crystal"],
  d: ["D"],
  dart: ["Dart"],
  ex: ["EX", "Elixir", "elixir"],
  fs: ["FS", "FSharp", "fsharp"],
  gleam: ["Gleam"],
  go: ["Go"],
  groovy: ["Groovy"],
  hs: ["HS", "Haskell", "haskell"],
  hx: ["HX", "Haxe", "haxe"],
  java: ["Java"],
  js: ["JS", "JavaScript", "javascript"],
  jl: ["JL", "Julia", "julia"],
  kt: ["KT", "Kotlin", "kotlin"],
  lua: ["Lua"],
  nim: ["Nim"],
  ocaml: ["OCAML", "caml"],
  php: ["PHP"],
  pas: ["PAS", "Pascal", "pascal"],
  pl: ["PL", "Perl", "perl"],
  t: ["PL", "T", "Perl", "perl"],
  py: ["PY", "Python", "python"],
  r: ["R"],
  rb: ["RB", "Ruby", "ruby"],
  rs: ["RS", "Rust", "rust"],
  sc: ["SC", "Scala", "scala"],
  ts: ["TS", "TypeScript", "typescript"],
  v: ["V"],
  zig: ["Zig"],
};
